### PR TITLE
feat(readme): add author notes to readme

### PR DESCRIPTION
**Pull request by dwieeb**
depends on https://github.com/ionic-team/create-capacitor-plugin/pull/22
resolves https://github.com/ionic-team/create-capacitor-plugin/issues/8

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I think it should include install instructions like `npm install {{{ PACKAGE_NAME }}}` and `npx cap sync`. Also manual android `MainActivity.java` changes. That's why I didn't add any other information on the PR where I added the README, because it's still unclear if we will manage to skip that part in Capacitor 3

**Comment by dwieeb** [comment]
Ah, I was thinking the README could be for the plugin developer at first, and then they'd change it. But thinking about this more, maybe these instructions should be in a separate markdown file and the README could be for what you're describing. 👍

**Comment by jcesarmobile** [comment]
Yeah, maybe in a CONTRIBUTING.md

**Comment by jcesarmobile** [comment]
I personally don’t like the idea of adding this notes, and also I don’t think it closes #8, that’s about install instructions of the plugin for users.

**Comment by dwieeb** [comment]
That's fine. Maybe #8 should be closed because we already have install instructions: https://github.com/ionic-team/create-capacitor-plugin/blob/main/assets/plugin-template/README.md.mustache

**Pull request closed without merging**
